- hosts: "${{ secrets.SERVER_IP }}"
  user: "${{ secrets.USER }}"
  tasks:
    - name: Stop the semaphore_mysql_1 container
      docker_container:
        name: semaphore_mysql_1
        state: stopped
